package com.beudbeud.fuji.data

/**
 * Builds a 3D LUT by observing what the camera did to an image.
 *
 * A RAF is developed twice — once neutral, once with the recipe — and every
 * pixel pair is one (input colour → output colour) sample. A single frame gives
 * millions of them, so no colour chart is needed.
 *
 * The catch is coverage: a scene only contains the colours it contains. Grid
 * cells no pixel landed in are filled from their neighbours, and cells the fill
 * cannot reach pass colour through unchanged. [coverage] reports how much of the
 * cube was actually measured, which is the honest quality figure for the result.
 *
 * Clarity and grain are spatial effects and cannot be represented here at all.
 */
class CubeLut(val size: Int = 33) {
    init { require(size in 2..64) { "LUT size $size out of range" } }

    private val cells = size * size * size
    private val sum = DoubleArray(cells * 3)
    private val hits = IntArray(cells)

    /** Red varies fastest, as the .cube format requires. */
    private fun index(r: Int, g: Int, b: Int) = (b * size + g) * size + r

    private fun quantize(v: Int) = (v.coerceIn(0, 255) * (size - 1) + 127) / 255

    /** Record that input colour [src] came out as [dst]. Channels are 0..255. */
    fun accumulate(srcR: Int, srcG: Int, srcB: Int, dstR: Int, dstG: Int, dstB: Int) {
        val i = index(quantize(srcR), quantize(srcG), quantize(srcB))
        sum[i * 3] += dstR / 255.0
        sum[i * 3 + 1] += dstG / 255.0
        sum[i * 3 + 2] += dstB / 255.0
        hits[i]++
    }

    /** Fraction of the cube that was measured rather than inferred, 0..1. */
    fun coverage(): Float = hits.count { it > 0 }.toFloat() / cells

    /**
     * Averaged samples, with unvisited cells grown from their filled neighbours.
     * Cells still unreached pass through unchanged, so the LUT degrades to the
     * identity in colours the frame never contained rather than to nonsense.
     */
    fun build(): FloatArray {
        val out = FloatArray(cells * 3)
        val filled = BooleanArray(cells)
        for (i in 0 until cells) {
            if (hits[i] == 0) continue
            filled[i] = true
            for (c in 0..2) out[i * 3 + c] = (sum[i * 3 + c] / hits[i]).toFloat()
        }
        // Dilate into the empty cells until the cube is full or nothing spreads
        repeat(size) {
            val pending = (0 until cells).filterNot { filled[it] }
            if (pending.isEmpty()) return@repeat
            val grown = mutableListOf<Pair<Int, FloatArray>>()
            for (i in pending) {
                val r = i % size
                val g = (i / size) % size
                val b = i / (size * size)
                val acc = FloatArray(3)
                var n = 0
                for ((dr, dg, db) in NEIGHBOURS) {
                    val nr = r + dr; val ng = g + dg; val nb = b + db
                    if (nr !in 0 until size || ng !in 0 until size || nb !in 0 until size) continue
                    val j = index(nr, ng, nb)
                    if (!filled[j]) continue
                    for (c in 0..2) acc[c] += out[j * 3 + c]
                    n++
                }
                if (n > 0) grown += i to FloatArray(3) { acc[it] / n }
            }
            if (grown.isEmpty()) return@repeat
            for ((i, v) in grown) {
                filled[i] = true
                for (c in 0..2) out[i * 3 + c] = v[c]
            }
        }
        // Never measured, never reached: leave the colour alone
        for (i in 0 until cells) {
            if (filled[i]) continue
            val r = i % size
            val g = (i / size) % size
            val b = i / (size * size)
            out[i * 3] = r.toFloat() / (size - 1)
            out[i * 3 + 1] = g.toFloat() / (size - 1)
            out[i * 3 + 2] = b.toFloat() / (size - 1)
        }
        return out
    }

    /** Adobe/Resolve .cube text — readable by Lightroom, Capture One, Darktable, Resolve. */
    fun toCubeText(title: String): String = buildString {
        appendLine("# Generated by Reshipi from an in-camera RAW conversion")
        appendLine("# Measured coverage: ${(coverage() * 100).toInt()}% of the colour cube")
        appendLine("TITLE \"${title.replace('"', '\'')}\"")
        appendLine("LUT_3D_SIZE $size")
        appendLine("DOMAIN_MIN 0.0 0.0 0.0")
        appendLine("DOMAIN_MAX 1.0 1.0 1.0")
        val grid = build()
        for (i in 0 until cells) {
            appendLine(
                "%.6f %.6f %.6f".format(
                    java.util.Locale.US, grid[i * 3], grid[i * 3 + 1], grid[i * 3 + 2],
                )
            )
        }
    }

    private companion object {
        val NEIGHBOURS = listOf(
            Triple(-1, 0, 0), Triple(1, 0, 0),
            Triple(0, -1, 0), Triple(0, 1, 0),
            Triple(0, 0, -1), Triple(0, 0, 1),
        )
    }
}
